In [0]:
File='/FileStore/tables/Department.csv'
df_pyspark = spark.read.csv(File ,header=True , inferSchema= True)

In [0]:
df_pyspark.show()

+--------+--------------------+------+
|    Name|          Department|Salary|
+--------+--------------------+------+
|   Teddi|Business Development| 15772|
|    Orin|            Services| 39992|
|  Robbyn|           Marketing| 20268|
| Pandora|          Accounting| 12551|
|  Tandie|          Accounting| 35615|
|    Abba|           Marketing| 35431|
|   Adrea|     Human Resources| 26432|
|Roseline|             Support| 26200|
| Beltran|Business Development| 37857|
| Rafaela|            Services| 20859|
|  Robina|         Engineering| 12624|
|  Lionel|Research and Deve...| 11167|
|   Ranee|          Accounting| 19623|
|  Geneva|            Training| 13264|
|  Perice|  Product Management| 23290|
|  Samara|               Sales| 14428|
| Adolpho|Research and Deve...| 41853|
|  Anjela|           Marketing| 24707|
|    Mela|               Sales| 20820|
|   Danie|Business Development| 16647|
+--------+--------------------+------+

In [0]:
## using GroupBy with Name
df_pyspark.groupBy('Name').sum().show()

+--------+-----------+
|    Name|sum(Salary)|
+--------+-----------+
|   Adrea|      26432|
| Pandora|      12551|
|Roseline|      26200|
|   Danie|      16647|
|  Robbyn|      20268|
| Rafaela|      20859|
|  Samara|      14428|
|  Lionel|      11167|
|  Perice|      23290|
|    Abba|      35431|
|  Tandie|      35615|
|    Mela|      20820|
| Beltran|      37857|
| Adolpho|      41853|
|  Anjela|      24707|
|  Robina|      12624|
|  Geneva|      13264|
|   Teddi|      15772|
|   Ranee|      19623|
|    Orin|      39992|
+--------+-----------+

In [0]:
## finding the maximum salary of a department
df_pyspark.groupBy('Department').sum().show()

+--------------------+-----------+
|          Department|sum(Salary)|
+--------------------+-----------+
|            Services|      60851|
|  Product Management|      23290|
|               Sales|      35248|
|         Engineering|      12624|
|          Accounting|      67789|
|Business Development|      70276|
|Research and Deve...|      53020|
|            Training|      13264|
|           Marketing|      80406|
|             Support|      26200|
|     Human Resources|      26432|
+--------------------+-----------+

In [0]:
## Using count function
df_pyspark.groupBy('Department').count().show()

+--------------------+-----+
|          Department|count|
+--------------------+-----+
|            Services|    2|
|  Product Management|    1|
|               Sales|    2|
|         Engineering|    1|
|          Accounting|    3|
|Business Development|    3|
|Research and Deve...|    2|
|            Training|    1|
|           Marketing|    3|
|             Support|    1|
|     Human Resources|    1|
+--------------------+-----+

In [0]:
## finding the sum off all the salary
df_pyspark.agg({'Salary':'sum'}).show()

+-----------+
|max(Salary)|
+-----------+
|      41853|
+-----------+

In [0]:
## finding the max salary
df_pyspark.agg({'Salary':'max'}).show()

+-----------+
|max(Salary)|
+-----------+
|      41853|
+-----------+

In [0]:
## finding the min salary
df_pyspark.agg({'Salary':'min'}).show()

+-----------+
|min(Salary)|
+-----------+
|      11167|
+-----------+

In [0]:
## finding the avg or mean salary
df_pyspark.agg({'Salary':'avg'}).show()
df_pyspark.agg({'Salary':'mean'}).show()

+-----------+
|avg(Salary)|
+-----------+
|    23470.0|
+-----------+

+-----------+
|avg(Salary)|
+-----------+
|    23470.0|
+-----------+

In [0]:
## getting the minimum salary of a department
df_pyspark.groupBy('Department').min().show()

+--------------------+-----------+
|          Department|min(Salary)|
+--------------------+-----------+
|            Services|      20859|
|  Product Management|      23290|
|               Sales|      14428|
|         Engineering|      12624|
|          Accounting|      12551|
|Business Development|      15772|
|Research and Deve...|      11167|
|            Training|      13264|
|           Marketing|      20268|
|             Support|      26200|
|     Human Resources|      26432|
+--------------------+-----------+

In [0]:
## getting the max salary in a department
df_pyspark.groupBy('Department').max().show()

+--------------------+-----------+
|          Department|max(Salary)|
+--------------------+-----------+
|            Services|      39992|
|  Product Management|      23290|
|               Sales|      20820|
|         Engineering|      12624|
|          Accounting|      35615|
|Business Development|      37857|
|Research and Deve...|      41853|
|            Training|      13264|
|           Marketing|      35431|
|             Support|      26200|
|     Human Resources|      26432|
+--------------------+-----------+

In [0]:
from pyspark.sql.functions import desc , asc
df_pyspark.groupBy('Department').max().sort(asc('max(Salary)')).show()

+--------------------+-----------+
|          Department|max(Salary)|
+--------------------+-----------+
|         Engineering|      12624|
|            Training|      13264|
|               Sales|      20820|
|  Product Management|      23290|
|             Support|      26200|
|     Human Resources|      26432|
|           Marketing|      35431|
|          Accounting|      35615|
|Business Development|      37857|
|            Services|      39992|
|Research and Deve...|      41853|
+--------------------+-----------+

In [0]:

from pyspark.sql.functions import sum, col, desc
df_pyspark.groupBy("Department") \
  .agg(sum("salary").alias("sum_salary")) \
  .filter(col("sum_salary") > 40000)  \
  .sort(desc("sum_salary")) \
  .show()

#+-----+----------+
#|state|sum_salary|
#+-----+----------+
#|   NY|    252000|
#|   CA|    171000|
#|   NV|    166000|
#+-----+----------+

+--------------------+----------+
|          Department|sum_salary|
+--------------------+----------+
|           Marketing|     80406|
|Business Development|     70276|
|          Accounting|     67789|
|            Services|     60851|
|Research and Deve...|     53020|
+--------------------+----------+

In [0]:
## using filter and sorting function with group by
from pyspark.sql.functions import *
df_pyspark.groupBy('Department') \
          .agg(sum('Salary') \
          .alias('Sum_Salary')) \
          .filter(col('Sum_Salary')>40000) \
          .sort(desc('Sum_Salary')).show()

+--------------------+----------+
|          Department|Sum_Salary|
+--------------------+----------+
|           Marketing|     80406|
|Business Development|     70276|
|          Accounting|     67789|
|            Services|     60851|
|Research and Deve...|     53020|
+--------------------+----------+

In [0]:
## dividing the above query into parts
df_groupby=df_pyspark.groupBy('Department').agg(sum('Salary').alias('Sum_Salary'))

df_filter=df_groupby.filter(col('Sum_Salary')>40000)

df_filter.sort('Sum_salary').show()

+--------------------+----------+
|          Department|Sum_Salary|
+--------------------+----------+
|Research and Deve...|     53020|
|            Services|     60851|
|          Accounting|     67789|
|Business Development|     70276|
|           Marketing|     80406|
+--------------------+----------+

In [0]:
## using two filter conditions in the same query

df_groupBy =df_pyspark.groupBy('Department').agg(sum('Salary').alias('Sum_Salary'))  ## group by and renaming the column
df_filter=df_groupBy.filter((col('Sum_Salary')>30000) &(col('Sum_Salary')<60000))    ## applying the filter

df_filter.sort(desc('Sum_Salary')).show() ## sorting and applying the filter

+--------------------+----------+
|          Department|Sum_Salary|
+--------------------+----------+
|Research and Deve...|     53020|
|               Sales|     35248|
+--------------------+----------+